### ISSUE TITLE
Use of register allocation before code emission

### ISSUE THREAD

**Issue by marcospampi** [MerryMage/DrGBA#1]
Hello MerryMage,
I'm impressed with your work with Dynarmic, and I'll sure be following this project too.
Though one thing I don't agree with Dynarmic is the register allocation, due to it being made on emission, and not as pass.
This makes code a bit ugly, and could cause more spills to take place.
One way to overcome this issue is adding three passes before emission: 
-pre-coloring
-liveness analysis
-coloring/register allocation
Basically, with pre-coloring you'd be just coloring those values in the IR which needs a specific register ( call arguments, results, x86 stuff )
With liveness analysis you'd just compute when X value is available ( the next instruction of its definition ), and when its use ends.
With coloring, you can use some sort of linear scan, you could imagine host registers as containers of non overlapping ranges: you first fill pre-colored values and then color the others, when needed you can spill/fill/copy values here.
Then in emission you just emit code.

Well these are bits and pieces from my head I fail to apply on my own, I'm not even sure you'd come up with such a complex system like Dynarmic for this project.

Still, looking forward to this project, have fun.

**Comment by MerryMage** [comment]
Hey! dynarmic's design could certainly be improved in many areas. And I do understand compiler theory, thanks. :p

There are several things I dislike about dynarmic's current design:

1. The lack of a proper register allocator.
    This was initially missed out because the original version of the JIT was part of a (very big) PR to Citra before it became it's own project, hence readability and understandability to those without previous compiler experience were goals. This is now, of course, not really a concern anymore.
    A major advantage of the current design is its speed. Compilation stutter in a non-tiered JIT can be noticeable, hence compilation speed is somewhat important. A disadvantage is the poor quality of allocation choices. A proper allocation pass certainly could certainly improve code quality. The current IR design has non-trivial register constraints in some areas though, which is why I've been putting this off for ages. Furthermore whether the cost of having one is worth it is another thing which puts me off.
2. Block level analysis instead of function level analysis.
    Function-level analysis would allow for values to be kept in host registers between basic blocks of a function instead of having to save/restore these at the start and end of every basic block. This will probably have a bigger `mov` saving compared to a new register allocator. This is something I feel has a clearer benefit.
3. Some micro-optimization around flag handling.
    Another source of unnecessary movement instructions is around saving and restoring flags. There is also some unnecessary unbundling of flags especially in the A32 frontend.
4. The overly high-level nature of the IR.
    This is something which bugs me occasionally. The IR maps very well to ARM-like architectures but poorly to anything else. I'm not sure I like the current design much anymore.

**Comment by MerryMage** [comment]
DrGBA will be a very different project to dynarmic.

dynarmic is something I've written for others to use, but DrGBA is something I'll poke and prod with for my own amusement.

---

The premise:

A lot of emulators sacrifice accuracy in some way in order for guest programs to run at a reasonable speed. This project is an experiment to hopefully demonstrate that perfect cycle-accuracy need not be at the cost of speed.

My goals in order of priority:

1. First and foremost, **cycle-accuracy** is a non-negotiable quality. Anything else will be sacrificed for this goal.
2. **Speed** is a secondary priority, coming after accuracy. I will try to make this as fast as possible without compromising guest-observable accuracy, hence the plan to implement a cycle-accurate dynamic recompiler.
3. Thirdly, **readability and maintainability**. I will do my best to make things not completely incomprehensible, but not where this would compromise speed too much.

I chose the GBA for several reasons:

* I enjoy the platform.
* It is a console from an era where games require accurate emulation to run properly.
* It is reasonably well understood, though there are some not-well-understood parts that I want to explore too.
* There are known inaccuracies in most GBA emulators, some of which exist because they are non-preformant to emulate accurately.
* The impetus for this project was from attempting to write a JIT for the mGBA. I wanted to write a JIT that retained accuracy. I came to the realisation that treating the CPU as a standalone component to JIT was the wrong approach.

The project will have a very GBA-oriented IR; the IR would not be purely concerned about CPU emulation but will also interleave PPU and APU behavior. Where most of the performance would come from would be from optimizations that will move things across cycle boundaries without affecting guest-observable behaviour.

Of course, it might turn out my ideas are simply unworkable. Discovery is part of the fun!

---

Having said all the above I don't really intend for anyone else to use this emulator. More mainstream GBA emulators already have sufficient game compatibility. This project should be treated more like an exploratory research project – a curiousity that I will tinker with in my free time – and not really something for public consumption.
